-- Baseline capturing prod schema drift (objects created directly on prod, no migration files).
-- Generated by `supabase db diff --linked` 2026-07-11, then hand-edited to REMOVE the
-- published_posts drop statements (that table is a NEW local feature not yet deployed;
-- the diff wanted to delete it only because prod lacks it).
-- PROD NOTE: prod already has everything in this file — mark it applied there via
-- `supabase migration repair --status applied 20260711052236` before any db push.
create sequence "public"."merchant_reviews_id_seq";



























alter table "public"."users" drop constraint "users_auth_user_id_fkey";

alter table "public"."users" drop constraint "users_auth_user_id_key";

drop function if exists "public"."get_user_role"(user_id uuid);

drop function if exists "public"."get_user_role_secure"(check_user_id uuid);

-- local DBs may still carry this trigger; prod does not (no-op there)
drop trigger if exists "on_auth_user_created" on "auth"."users";

drop function if exists "public"."handle_new_user"();

drop function if exists "public"."is_user_banned"(check_user_id uuid);

drop function if exists "public"."log_audit_event"(p_action text, p_target_type text, p_target_id text, p_details jsonb, p_ip_address inet, p_user_agent text);

drop function if exists "public"."migrate_users_to_auth"();




drop index if exists "public"."idx_users_auth_user_id";


drop index if exists "public"."users_auth_user_id_key";


create table "public"."merchant_reviews" (
    "id" integer not null default nextval('merchant_reviews_id_seq'::regclass),
    "merchant_id" integer not null,
    "platform" character varying(50) not null,
    "review_text" text not null,
    "is_active" boolean not null default true,
    "created_at" timestamp without time zone default CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone default CURRENT_TIMESTAMP
);


alter table "public"."merchant_reviews" enable row level security;

alter table "public"."link_clicks" enable row level security;

alter table "public"."merchant_details" enable row level security;

alter table "public"."merchants" enable row level security;

alter table "public"."page_views" enable row level security;

alter table "public"."users" drop column "auth_user_id";

alter table "public"."users" enable row level security;

alter sequence "public"."merchant_reviews_id_seq" owned by "public"."merchant_reviews"."id";


CREATE INDEX idx_merchant_reviews_is_active ON public.merchant_reviews USING btree (is_active);

CREATE INDEX idx_merchant_reviews_merchant_id ON public.merchant_reviews USING btree (merchant_id);

CREATE INDEX idx_merchant_reviews_merchant_platform_active ON public.merchant_reviews USING btree (merchant_id, platform, is_active);

CREATE INDEX idx_merchant_reviews_platform ON public.merchant_reviews USING btree (platform);

CREATE UNIQUE INDEX merchant_reviews_pkey ON public.merchant_reviews USING btree (id);

alter table "public"."merchant_reviews" add constraint "merchant_reviews_pkey" PRIMARY KEY using index "merchant_reviews_pkey";

alter table "public"."merchant_reviews" add constraint "merchant_reviews_merchant_id_fkey" FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE CASCADE not valid;

alter table "public"."merchant_reviews" validate constraint "merchant_reviews_merchant_id_fkey";

alter table "public"."merchant_reviews" add constraint "merchant_reviews_platform_check" CHECK (((platform)::text = ANY ((ARRAY['google'::character varying, 'facebook'::character varying])::text[]))) not valid;

alter table "public"."merchant_reviews" validate constraint "merchant_reviews_platform_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_user_role(user_uuid uuid)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    user_role TEXT;
BEGIN
    SELECT role INTO user_role 
    FROM public.user_roles 
    WHERE user_roles.user_id = get_user_role.user_uuid;
    
    RETURN COALESCE(user_role, 'merchant');
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_user_role_secure(user_uuid uuid)
 RETURNS user_role_enum
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    user_role user_role_enum;
BEGIN
    SELECT role INTO user_role 
    FROM public.user_roles 
    WHERE user_roles.user_id = get_user_role_secure.user_uuid;
    
    RETURN COALESCE(user_role, 'merchant'::user_role_enum);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.is_user_banned(user_uuid uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    banned_until TIMESTAMP WITH TIME ZONE;
BEGIN
    SELECT user_roles.banned_until INTO banned_until
    FROM public.user_roles
    WHERE user_roles.user_id = is_user_banned.user_uuid;
    
    RETURN COALESCE(banned_until > NOW(), false);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.log_audit_event(p_user_id uuid, p_action text, p_target_type text DEFAULT NULL::text, p_target_id text DEFAULT NULL::text, p_details jsonb DEFAULT NULL::jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    audit_id BIGINT;
    user_email TEXT;
    request_headers JSONB;
BEGIN
    -- Get user email from auth.users
    SELECT email INTO user_email
    FROM auth.users
    WHERE id = p_user_id;
    
    -- Try to get headers from current_setting
    BEGIN
        request_headers := current_setting('request.headers', true)::jsonb;
    EXCEPTION
        WHEN OTHERS THEN
            request_headers := '{}'::jsonb;
    END;
    
    -- Insert audit record
    INSERT INTO public.audit_logs (
        user_id,
        user_email,
        action,
        target_type,
        target_id,
        details,
        ip_address,
        user_agent
    ) VALUES (
        p_user_id,
        user_email,
        p_action,
        p_target_type,
        p_target_id,
        p_details,
        inet_client_addr(),
        COALESCE(request_headers->>'user-agent', '')
    ) RETURNING id INTO audit_id;
    
    RETURN audit_id;
EXCEPTION
    WHEN OTHERS THEN
        -- Log the error but don't fail the operation
        RAISE WARNING 'Failed to log audit event: %', SQLERRM;
        RETURN NULL;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.migrate_users_to_auth()
 RETURNS TABLE(success boolean, message text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    migrated_count INTEGER := 0;
    user_record RECORD;
    auth_user_id UUID;
BEGIN
    -- Only proceed if users table has data
    IF NOT EXISTS (SELECT 1 FROM public.users LIMIT 1) THEN
        RETURN QUERY SELECT true, 'No users to migrate'::TEXT;
        RETURN;
    END IF;
    
    -- Migrate each user
    FOR user_record IN SELECT * FROM public.users LOOP
        -- Create auth user
        INSERT INTO auth.users (
            id,
            email,
            created_at,
            updated_at
        ) VALUES (
            gen_random_uuid(),
            user_record.email,
            COALESCE(user_record.created_at, NOW()),
            COALESCE(user_record.updated_at, NOW())
        ) ON CONFLICT (email) DO NOTHING
        RETURNING id INTO auth_user_id;
        
        -- Get the user ID if already exists
        IF auth_user_id IS NULL THEN
            SELECT id INTO auth_user_id 
            FROM auth.users 
            WHERE email = user_record.email;
        END IF;
        
        -- Insert into user_roles
        INSERT INTO public.user_roles (user_id, role) 
        VALUES (auth_user_id, user_record.role::user_role_enum)
        ON CONFLICT (user_id) DO UPDATE
        SET role = EXCLUDED.role;
        
        migrated_count := migrated_count + 1;
    END LOOP;
    
    RETURN QUERY SELECT true, format('Migrated %s users', migrated_count)::TEXT;
END;
$function$
;

grant delete on table "public"."merchant_reviews" to "anon";

grant insert on table "public"."merchant_reviews" to "anon";

grant references on table "public"."merchant_reviews" to "anon";

grant select on table "public"."merchant_reviews" to "anon";

grant trigger on table "public"."merchant_reviews" to "anon";

grant truncate on table "public"."merchant_reviews" to "anon";

grant update on table "public"."merchant_reviews" to "anon";

grant delete on table "public"."merchant_reviews" to "authenticated";

grant insert on table "public"."merchant_reviews" to "authenticated";

grant references on table "public"."merchant_reviews" to "authenticated";

grant select on table "public"."merchant_reviews" to "authenticated";

grant trigger on table "public"."merchant_reviews" to "authenticated";

grant truncate on table "public"."merchant_reviews" to "authenticated";

grant update on table "public"."merchant_reviews" to "authenticated";

grant delete on table "public"."merchant_reviews" to "service_role";

grant insert on table "public"."merchant_reviews" to "service_role";

grant references on table "public"."merchant_reviews" to "service_role";

grant select on table "public"."merchant_reviews" to "service_role";

grant trigger on table "public"."merchant_reviews" to "service_role";

grant truncate on table "public"."merchant_reviews" to "service_role";

grant update on table "public"."merchant_reviews" to "service_role";

create policy "Admins can view all link clicks"
on "public"."link_clicks"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM user_roles
  WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::user_role_enum, 'superadmin'::user_role_enum]))))));


create policy "Merchants can view own link clicks"
on "public"."link_clicks"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM merchants
  WHERE ((merchants.id = link_clicks.merchant_id) AND (merchants.auth_user_id = auth.uid())))));


create policy "Public can insert link clicks"
on "public"."link_clicks"
as permissive
for insert
to public
with check (true);


create policy "Admins can update all details"
on "public"."merchant_details"
as permissive
for update
to public
using ((EXISTS ( SELECT 1
   FROM user_roles
  WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::user_role_enum, 'superadmin'::user_role_enum]))))));


create policy "Admins can view all details"
on "public"."merchant_details"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM user_roles
  WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::user_role_enum, 'superadmin'::user_role_enum]))))));


create policy "Merchants can insert own details"
on "public"."merchant_details"
as permissive
for insert
to public
with check ((EXISTS ( SELECT 1
   FROM merchants
  WHERE ((merchants.id = merchant_details.merchant_id) AND (merchants.auth_user_id = auth.uid())))));


create policy "Merchants can update own details"
on "public"."merchant_details"
as permissive
for update
to public
using ((EXISTS ( SELECT 1
   FROM merchants
  WHERE ((merchants.id = merchant_details.merchant_id) AND (merchants.auth_user_id = auth.uid())))));


create policy "Merchants can view own details"
on "public"."merchant_details"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM merchants
  WHERE ((merchants.id = merchant_details.merchant_id) AND (merchants.auth_user_id = auth.uid())))));


create policy "Public can view merchant details"
on "public"."merchant_details"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM merchants
  WHERE ((merchants.id = merchant_details.merchant_id) AND (merchants.is_active = true)))));


create policy "Admins can update all reviews"
on "public"."merchant_reviews"
as permissive
for update
to public
using ((EXISTS ( SELECT 1
   FROM user_roles
  WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::user_role_enum, 'superadmin'::user_role_enum]))))));


create policy "Admins can view all reviews"
on "public"."merchant_reviews"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM user_roles
  WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::user_role_enum, 'superadmin'::user_role_enum]))))));


create policy "Merchants can insert own reviews"
on "public"."merchant_reviews"
as permissive
for insert
to public
with check ((EXISTS ( SELECT 1
   FROM merchants
  WHERE ((merchants.id = merchant_reviews.merchant_id) AND (merchants.auth_user_id = auth.uid())))));


create policy "Merchants can update own reviews"
on "public"."merchant_reviews"
as permissive
for update
to public
using ((EXISTS ( SELECT 1
   FROM merchants
  WHERE ((merchants.id = merchant_reviews.merchant_id) AND (merchants.auth_user_id = auth.uid())))));


create policy "Merchants can view own reviews"
on "public"."merchant_reviews"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM merchants
  WHERE ((merchants.id = merchant_reviews.merchant_id) AND (merchants.auth_user_id = auth.uid())))));


create policy "Public can view active reviews"
on "public"."merchant_reviews"
as permissive
for select
to public
using ((is_active = true));


create policy "Admins can update all merchants"
on "public"."merchants"
as permissive
for update
to public
using ((EXISTS ( SELECT 1
   FROM user_roles
  WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::user_role_enum, 'superadmin'::user_role_enum]))))));


create policy "Admins can view all merchants"
on "public"."merchants"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM user_roles
  WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::user_role_enum, 'superadmin'::user_role_enum]))))));


create policy "Merchants can update own merchant"
on "public"."merchants"
as permissive
for update
to public
using ((auth.uid() = auth_user_id));


create policy "Merchants can view own merchant"
on "public"."merchants"
as permissive
for select
to public
using ((auth.uid() = auth_user_id));


create policy "Public can view active merchants"
on "public"."merchants"
as permissive
for select
to public
using ((is_active = true));


create policy "Users can insert own merchant"
on "public"."merchants"
as permissive
for insert
to public
with check ((auth.uid() = auth_user_id));


create policy "Admins can view all page views"
on "public"."page_views"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM user_roles
  WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::user_role_enum, 'superadmin'::user_role_enum]))))));


create policy "Merchants can view own page views"
on "public"."page_views"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM merchants
  WHERE ((merchants.id = page_views.merchant_id) AND (merchants.auth_user_id = auth.uid())))));


create policy "Public can insert page views"
on "public"."page_views"
as permissive
for insert
to public
with check (true);


create policy "Admins can update all users"
on "public"."users"
as permissive
for update
to public
using ((EXISTS ( SELECT 1
   FROM user_roles
  WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::user_role_enum, 'superadmin'::user_role_enum]))))));


create policy "Admins can view all users"
on "public"."users"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM user_roles
  WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::user_role_enum, 'superadmin'::user_role_enum]))))));


CREATE TRIGGER update_merchant_reviews_updated_at BEFORE UPDATE ON public.merchant_reviews FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


